# Generated by Django 2.0.7 on 2018-07-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0002_auto_20180712_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='img',
            field=models.ImageField(default='', upload_to='notes-img'),
            preserve_default=False,
        ),
    ]
