# Generated by Django 2.0.7 on 2018-07-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0003_note_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='img',
            field=models.ImageField(blank=True, upload_to='notes-img'),
        ),
    ]
