# Generated by Django 2.0.7 on 2018-07-19 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180719_0102'),
    ]

    operations = [
    ]
